language: scala
scala:
- 2.10.0
script: ./sbt test
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: DLv7D0NG3JytiDxeFyfouUzInRslDlK2beruN0nOtg2gVOLSLwPqmxMsGG3v4hiSlsbPcNorXXQ5vwBZL6LZCBwl/ERTwvNI3FXgBERgsNrR+pRRYJBSTmxqx2gp4wuhHZnqvyHF/rjO+uTxjeY8GiW6eKUpoNplOvC8VCUi5Ro=
