language: scala
scala:
- 2.10.0
script: "./sbt test"
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: UDpa39WfJvhpGKQHI96tMt2zjBLrrvcAJ+ny9mxlQjybfagGovJ2fNqfmN0tDrNOhaKqUNrgC8UenIlvp6S3wN6NacLaFazR9yBiSUwwHB3U648l5Swd3JkhJRQwtZp3QoSs5D6RypIm39mYNdYipAe4aWhvtnhHQagOkemVSO0=
  app: sphere-fedora
  on:
    repo: commercetools/sphere-fedora